languageCode = "zh-cn"
languageName = "中文"
languageDirection = "ltr"
weight = 1

title = "无限求索"
copyright = "© 2024-2025 InfMax | [陕ICP备2025064778号-2](https://beian.miit.gov.cn/) "

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog", "newsletter"]
  description = "infinite seeking tools,ideas,techs and interesting things"

[params.author]
name = "终南山葫芦娃"
image = "img/author.png"
headline = "Love tech, Love life"
bio = "Keep learning, Keep sharing"
links = [
 { email = "lzjqsdd@gmail.com" },
 {xiaohongshu = "https://www.xiaohongshu.com/user/profile/61fbdcbd000000001000cf59"},
 {bilibili = "https://space.bilibili.com/4526017"},
 # { link = "https://infmax.top/" },
  {zhihu = "https://www.zhihu.com/people/lzjqsdd"},
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
 { github = "https://github.com/infmax-top" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  { telegram = "https://t.me/infmaxtop" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  { x-twitter = "https://twitter.com/infmaxtop" },
  #   { youtube = "https://youtube.com/username" },
]
